version: '3.1'

services:

  opencartapp:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
          TIMEZONE: America/Panama
    image: opencartapp
    volumes:
      - ./opencartapp:/opencartapp
      - ./storageout:/storageout
      - ./conf:/conf
    ports:
      - 80:80
      - 443:443
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin2023
      MARIADB_DATABASE: storefrontdatos
    volumes:
      - ./opencartdb/create_db_user.sql:/docker-entrypoint-initdb.d/create_db_user.sql
      - ./opencartdb/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
